version: "3.3"

services:
  greekoffers:
    build:
      context: ./../
      dockerfile: build/Dockerfile
    restart: on-failure
    env_file:
      - ./../.env
    depends_on:
      - elk
      - tor

  elk:
    image: sebp/elk
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
  tor:
    build:
      context: ./../
      dockerfile: build/tor/Dockerfile
    restart: on-failure
    ports:
      - "9050:9050"
      - "8118:8118"